services:
  tmp-files-blue:
    image: ghcr.io/andywijaya15/tmp-files:latest
    container_name: tmp-files-blue
    volumes:
      - ./tmp:/app/tmp
      - ./static:/app/static
    ports:
      - "${PORT1}:3003"
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  tmp-files-green:
    image: ghcr.io/andywijaya15/tmp-files:latest
    container_name: tmp-files-green
    volumes:
      - ./tmp:/app/tmp
      - ./static:/app/static
    ports:
      - "${PORT2}:3003"
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --cleanup
