services:
  tmp-files:
    image: ghcr.io/andywijaya15/tmp-files:latest
    container_name: tmp-files
    volumes:
      - ./tmp:/app/tmp
      - ./static:/app/static
    ports:
      - "3003:3003"
    restart: unless-stopped
