services:
  tmp-files:
    image: ghcr.io/andywijaya15/tmp-files:latest
    container_name: tmp-files
    volumes:
      - ./tmp:/app/tmp
      - ./static:/app/static
    expose:
      - "3003"
    restart: unless-stopped

  caddy:
    image: caddy:latest
    container_name: caddy-tmp-files
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - tmp-files
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
